name: Deploy Next.js to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_PRIVATE_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image to Google Container Registry (GCR)
        run: |
          gcloud auth configure-docker europe-west2-docker.pkg.dev
          docker build --no-cache -t gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.GCP_IMAGE_NAME }}:latest .
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.GCP_IMAGE_NAME }}:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_SERVICE_NAME }} --image gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.GCP_IMAGE_NAME }}:latest --platform managed --region ${{ secrets.GCP_REGION }} --allow-unauthenticated
