- name: Login to Google Cloud
  uses: google-github-actions/setup-gcloud@v0.2.0
  with:
    project_id: ${{ secrets.PROJECT_ID }}
    service_account_key: ${{ secrets.GCP_SA_PRIVATE_KEY }}
    export_default_credentials: true

- name: Build and push Docker image to Google Container Registry (GCR)
  run: |
    gcloud auth configure-docker
    docker build -t gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.GCP_IMAGE_NAME }}:latest .
    docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ var.GCP_IMAGE_NAME }}:latest

- name: Deploy to Google Cloud Run
  run: |
    gcloud run deploy ${{ var.GCP_IMAGE_NAME }} --image gcr.io/${{ secrets.PROJECT_ID }}/${{ var.GCP_IMAGE_NAME }}:latest --platform managed --region ${{ var.GCP_REGION }} --allow-unauthenticated
