name: Deploy Next.js to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: rosy-strata-400307
          service_account_key: ${{ secrets.GCP_SA_PRIVATE_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image to Google Container Registry (GCR)
        run: |
          gcloud auth configure-docker europe-west2-docker.pkg.dev
          docker build --no-cache -t europe-west2-docker.pkg.dev/rosy-strata-400307/riscotto-nextjs:latest .
          docker push europe-west2-docker.pkg.dev/rosy-strata-400307/riscotto-nextjs:latest

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy riscotto-nextjs --image europe-west2-docker.pkg.dev/rosy-strata-400307/riscotto-nextjs:latest --platform managed --region europe-west2 --allow-unauthenticated
