name: Destroy Service on Google Cloud

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "CONFIRM" to proceed with the destruction of the service.'
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check confirmation
        run: |
          if [[ "${{ github.event.inputs.confirmation }}" != "CONFIRM" ]]; then
            echo "Destruction not confirmed. Exiting."
            exit 1
          fi

      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: rosy-strata-400307
          service_account_key: ${{ secrets.GCP_SA_PRIVATE_KEY }}
          export_default_credentials: true

      - name: Destroy the Google Cloud Run service
        run: |
          gcloud run services delete riscotto-nextjs --platform managed --region europe-west2 --quiet
